resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: BrainOS/pipeline-templates


trigger:
  - master

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)
pool:
    name: 'JioBuildAgent'

jobs:
  - template: java/java-maven-ci.yml@pipeline-templates
    parameters:
      # RUN-CI: ${{ variables.RUN-CI }}
      run_ci: 'true'
      run_sonar: $(Sonar)
      run_secops: $(SecOpsFortify)
      run_release: $(Release)
      sonar_project_name: 'jio-enterprise-ram-upload'
      sonar_project_key: 'jio-enterprise-ram-upload'
      sonar_project_version: 'jio-enterprise-ram-upload'